version: '2'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    image: angular-clonecademy:dev
    command: npm start
    volumes:
      - .:/angular
    ports:
      - "3000:3000"
