version: '2'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    image: angular-clonecademy:dev
    command: ng serve --host 0.0.0.0 --port 3000
    volumes:
      - .:/clonecademy-client
    ports:
      - "3000:3000"
