 version: '2'
 services:
   db:
     image: postgres
   django:
    build:
      context: .
      dockerfile: Dockerfile
    image: django-clonecademy:dev
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    depends_on:
      - db
