 version: '2'
 services:
   django:
    build:
      context: .
      dockerfile: Dockerfile
    image: django-clonecademy:dev
    command: /bin/bash /setup/setup.sh
    volumes:
      - /home/iliricon/clonecademy/database:/home/docker/django/database
    ports:
      - "80:80"

