 version: '2'
 services:
   django:
    environment:
      - ADMIN_PASSWD=admin
    build:
      context: .
      dockerfile: Dockerfile
    image: django-clonecademy:dev
    command: /bin/bash /setup/setup.sh
    volumes:
      - .:/django
    ports:
      - "80:80"

